### ISSUE TITLE
Using HexCode for Horizon custom colours.

### ISSUE THREAD

**Issue by PurpleDonuts** [Fchat-Horizon/Horizon#30]
I have no idea if this would work with the current f-chat system. However using Hex / RGB values instead of being restricted through f-chat's colours.

**Comment by PurpleDonuts** [comment]
Thanks, Github for now allowing me to use a label with this.

**Comment by FatCatClient** [comment]
On a technical level, this would be fairly easy to implement: simply have a different value on the profile that it'd need to parse as a hex color. Then all you'd need is to figure out a way to put this on a profile in a non-intrusive way and have the color-changing code (which now adds a CSS class), just set the color value of the name directly.

The issue I'm personally seeing with this is legibility; since an arbitrary text color against a (mostly) arbitrary background color means there's a big chance there's too little contrast, or another reason the text just becomes a nightmare to read. You _could_ make it so that there's a CSS text shadow surrounding custom names using the inverted color to always guarantee _some_ level of contrast, but I don't know if that'd look particularly appealing or not.

![Image](https://github.com/user-attachments/assets/0c36b692-0db4-406b-a418-f1950a317602)
```css
body {
  font-family: arial;
  background-color: #191932;
}

.contrast-text {
  color: #191932;
  text-shadow: 0px 2px 0px #e6e6cd, 0px -2px 0px #e6e6cd, 2px 0px 0px #e6e6cd,
    -2px 0px 0px #e6e6cd;
  font-size: 1.5em;
}
```

![Image](https://github.com/user-attachments/assets/46b1f29d-e522-49f8-85ba-9f6d1fb598b0)
Text: #f4c3fa Border: #0b3c05
```css
body {
  font-family: arial;
  background-color: #191932;
}

.contrast-text {
  color: #f4c3fa;
  text-shadow: 0px 2px 0px #0b3c05, 0px -2px 0px #0b3c05, 2px 0px 0px #0b3c05,
    -2px 0px 0px #0b3c05;
  font-size: 1.5em;
}
```

I think Roleplay.Chat has custom colours for character names, so we should probably check out how/ if they solved this issue.
